name = "Soundcore Space One Pro"
mac_address = "00:00:00:00:30:62"
rfcomm_uuid = "0CF12D31-FAC3-4553-BD80-D6832E7B3062"

[[responses]]
command = [1, 1]
response = [
    9,    # battery level (0=10%, 9=100%)
    255,  # battery charging
    48,   # firmware version start
    51,
    46,
    51,
    55,   # firmware version end
    51,   # serial number start
    48,
    54,
    50,
    68,
    66,
    50,
    49,
    50,
    67,
    49,
    51,
    69,
    57,
    55,
    67,   # serial number end
    5,    # EQ preset
    0,    # EQ preset
    90,   # volume adjustments start
    140,
    160,
    160,
    150,
    140,
    120,
    100,
    120,
    0,    # volume adjustments end
    30,   # unknown
    0,    # hear id initialized
    1,    # hear id enabled
    120,  # hear id start
    120,
    120,
    120,
    120,
    120,
    120,
    120,
    120,
    0,    # hear id end
    0,    # hear id time start?
    0,
    0,
    0,    # hear id time end?
    2,    # hear id type (0=initial, 1=custom, 2=favorite music genre)
    130,  # hear id start
    130,
    130,
    130,
    130,
    130,
    130,
    130,
    130,
    0,    # hear id end
    0,    # hear id favorite music genre
    0,    # hear id favorite music genre
    4,    # unknown
    4,    # unknown
    7,    # press twice (7=bassup on/off, 15=none)
    3,    # ambient sound mode cycle
    1,    # 0=noise canceling, 1=transparency, 2=normal
    0x50, # custom noise canceling
    1,    # transparency mode (always 1)
    1,    # 0=custom noise canceling, 1=adaptive noise canceling
    0,    # wind noise reduction
    5,    # custom transparency
    0x31, # unknown
    1,    # low battery prompt
    0,    # dolby audio
    0,    # LDAC
    1,    # dual connections
    1,    # auto power off
    1,    # auto power off duration
    0,    # safe volume enabled
    90,   # safe volume limit
    0,    # safe volume refresh rate
    0,    # side tone
    1,    # ambient sound mode voice prompt
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
]
