name = "Soundcore Space One Pro"
mac_address = "00:00:00:00:30:62"
rfcomm_uuid = "0CF12D31-FAC3-4553-BD80-D6832E7B3062"

[[responses]]
command = [1, 1]
response = [
    4,
    255,
    48,
    51,
    46,
    51,
    55,
    51,
    48,
    54,
    50,
    68,
    66,
    50,
    49,
    50,
    67,
    49,
    51,
    69,
    57,
    55,
    67,
    5,
    0,
    90,
    140,
    160,
    160,
    150,
    140,
    120,
    100,
    120,
    0,
    30,
    255,
    0,
    255,
    255,
    255,
    255,
    255,
    255,
    255,
    255,
    255,
    0,
    0,
    0,
    0,
    0,
    0,
    255,
    255,
    255,
    255,
    255,
    255,
    255,
    255,
    255,
    0,
    0,
    0,
    4,
    4,
    7,
    3,
    1,
    80,
    1,
    1,
    0,
    5,
    49,
    1,
    1,
    0,
    1,
    1,
    1,
    0,
    90,
    0,
    0,
    1,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
]
