name = "Soundcore Liberty Air 2 Pro"
rfcomm_uuid = "00001101-0000-1000-8000-00805f9b34fb"

[[responses]]
# State update
command = [1, 1]
response = [
    0,
    1,
    0,
    0,
    4,
    5,
    0,
    0,
    120,
    120,
    120,
    120,
    120,
    120,
    120,
    120,
    120,
    120,
    120,
    120,
    120,
    120,
    120,
    120,
    0,
    0,
    0,
    120,
    120,
    120,
    120,
    120,
    120,
    120,
    120,
    120,
    120,
    120,
    120,
    120,
    120,
    120,
    120,
    0,
    0,
    0,
    0,
    0,
    0,
    120,
    120,
    120,
    120,
    120,
    120,
    120,
    120,
    120,
    120,
    120,
    120,
    120,
    120,
    120,
    120,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    1,
    0,
    0,
    0,
    0,
]


[[responses]]
# firmware version
command = [1, 5]
response = [
    48,
    48,
    46,
    48,
    48,
    48,
    48,
    46,
    48,
    48,
    48,
    48,
    48,
    48,
    48,
    48,
    48,
    48,
    48,
    48,
    48,
    48,
    48,
    48,
    48,
    48,
]
