name = "soundcore Sleep A30"
mac_address = "00:00:00:0d:13:01"
rfcomm_uuid = "0CF12D31-FAC3-4553-BD80-D6832E7D1301"

[[responses]]
command = [1, 1]
response = [
    1,
    1,
    9,
    9,
    48,  # left FW start
    49,
    46,
    48,
    48,  # left FW end
    48,  # right FW start
    49,
    46,
    48,
    48,  # right FW end
    49,  # SN start
    51,
    48,
    49,
    48,
    48,
    48,
    48,
    48,
    48,
    48,
    48,
    48,
    48,
    48,
    48,  # SN end
    223,
    186,
    112,
    217,
    191,
    144,
    48,
    49,
    46,
    48,
    48,
    0,
    0,
    0,
    0,
    6,
    221,
    102,
    17,
    0,
    255,
    255,
    255,
    255,
    255,
    255,
    255,
    255,
    0,
    30,
    0,
    1,
    255,
    255,
    255,
    0,
    0,
    1,
    0,
    0,
    50,
    17,
    1,
    0,
    6,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    1,
    203,
    49,
    61,
    0,
    0,
    0,
    0,
    0,
    2,
    2,
    1,
    128,
    0,
    0,
    0,
    0,
    0,
    0,
    4,
    3,
    2,
    128,
    0,
    0,
    0,
    0,
    0,
    0,
    4,
    4,
    3,
    128,
    0,
    0,
    0,
    0,
    0,
    0,
    4,
    5,
    4,
    128,
    0,
    0,
    0,
    0,
    0,
    0,
    4,
    1,
    0,
    0,
    1,
    8,
    0,
    0,
    0,
    1,
    1,
    0,
    0,
    1,
    1,
    0,
]

[[responses]]
command = [21, 3]
response = [0, 30, 0, 1, 0, 0, 0, 0]

[[responses]]
command = [1, 166]
response = [249, 243, 79, 106, 14, 112, 227, 230, 106, 12]

[[responses]]
command = [20, 1]
response = [0, 0, 149, 1, 0, 2, 50, 10]

[[responses]]
command = [20, 2]
response = [255, 255, 255, 255, 255, 255, 255, 255]

[[responses]]
command = [21, 4]
response = [
    [
        1,
        0,
        1,
        16,
        223,
        13,
        79,
        106,
        50,
        0,
        0,
        123,
        30,
        79,
        106,
        51,
        2,
        1,
        230,
        38,
        79,
        106,
        66,
        1,
        1,
        164,
        42,
        79,
        106,
        1,
        3,
        0,
        234,
        45,
        79,
        106,
        66,
        0,
        0,
        107,
        60,
        79,
        106,
        67,
        1,
        1,
        95,
        68,
        79,
        106,
        34,
        2,
        1,
        132,
        84,
        79,
        106,
        67,
        4,
        1,
        169,
        89,
        79,
        106,
        1,
        1,
        1,
        27,
        94,
        79,
        106,
        66,
        0,
        0,
        215,
        108,
        79,
        106,
        51,
        1,
        0,
        203,
        116,
        79,
        106,
        34,
        1,
        0,
        42,
        129,
        79,
        106,
        52,
        5,
        0,
        15,
        239,
        79,
        106,
        34,
        0,
        0,
        25,
        242,
        79,
        106,
        35,
        0,
        0,
        245,
        242,
        79,
        106,
        36,
        0,
        0,
    ],
    [
        2,
        4,
        32,
        184,
        0,
        180,
        0,
        66,
        0,
        121,
        239,
        94,
        1,
        9,
        255,
        0,
        0,
        1,
        21,
        4,
        175,
        0,
        0,
        0,
        1,
        23,
        80,
        250,
        78,
        106,
        18,
        0,
        0,
        65,
        251,
        78,
        106,
        1,
        1,
        0,
        63,
        252,
        78,
        106,
        4,
        0,
        0,
        179,
        12,
        79,
        106,
        18,
        0,
        0,
        58,
        27,
        79,
        106,
        19,
        2,
        0,
        247,
        34,
        79,
        106,
        18,
        0,
        1,
        119,
        42,
        79,
        106,
        1,
        2,
        0,
        251,
        45,
        79,
        106,
        18,
        0,
        0,
        131,
        60,
        79,
        106,
        19,
        1,
        1,
        123,
        68,
        79,
        106,
        34,
        1,
        1,
        168,
        84,
        79,
        106,
        35,
        2,
        1,
        146,
        89,
        79,
        106,
        1,
        2,
        1,
        6,
        94,
        79,
        106,
        18,
        0,
        0,
        21,
        108,
        79,
        106,
        19,
        0,
        0,
        209,
        115,
        79,
        106,
        34,
        1,
        0,
        59,
        117,
        79,
        106,
        1,
        0,
        0,
        81,
        123,
        79,
        106,
        18,
        0,
        0,
        17,
        127,
        79,
        106,
        1,
        2,
        0,
        62,
        128,
        79,
        106,
        18,
        0,
        0,
        237,
        128,
        79,
        106,
        20,
        0,
        0,
        219,
        238,
        79,
        106,
        50,
        0,
        0,
        231,
        241,
        79,
        106,
        51,
        0,
        0,
        192,
        242,
        79,
        106,
        52,
        0,
        0,
        59,
        43,
    ],
]
