name = "soundcore Sleep A30"
mac_address = "00:00:00:0d:13:01"
rfcomm_uuid = "0CF12D31-FAC3-4553-BD80-D6832E7D1301"

[[responses]]
command = [1, 1]
response = [
    1,    # host device
    1,    # tws connected
    9,    # left battery (0-9, 0=10%)
    9,    # right battery
    56,   # left FW start
    49,
    46,
    48,
    48,   # left FW end
    56,   # right FW start
    49,
    46,
    48,
    48,   # right FW end
    49,   # SN start
    51,
    48,
    49,
    48,
    48,
    48,
    48,
    48,
    48,
    48,
    48,
    48,
    48,
    48,
    48,   # SN end
    223,
    186,
    112,
    217,
    191,
    144,
    48,   # charging case FW start
    49,
    46,
    48,
    48,   # charging case FW end
    0,
    0,
    0,
    0,
    6,
    0xdd, # left double tap
    0x66, # right double tap
    0x00, # left tap 3 times
    0x00, # right tap 3 times
    255,
    255,
    255,
    255,
    255,
    255,
    255,
    255,
    0,
    30,
    0,
    1,
    255,
    255,
    255,
    0,    # listening mode (0=bluetooth, 1=local)
    0,    # default listening mode (0=bluetooth, 1=local)
    0,
    0,
    0,    # low battery prompt
    50,
    17,
    1,
    0,
    6,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    1,
    203,
    49,
    61,
    0,
    0,
    0,
    0,
    0,
    2,
    2,
    1,
    128,
    0,
    0,
    0,
    0,
    0,
    0,
    4,
    3,
    2,
    128,
    0,
    0,
    0,
    0,
    0,
    0,
    4,
    4,
    3,
    128,
    0,
    0,
    0,
    0,
    0,
    0,
    4,
    5,
    4,
    128,
    0,
    0,
    0,
    0,
    0,
    0,
    4,
    1,
    0,
    0,    # auto-off prompt tone (sound when earbuds auto power off)
    1,    # listening mode (Bluetooth/Local) change voice prompt
    8,
    0,    # Active noise canceling
    0,    # enable incoming calls during bluetooth mode
    0,
    1,
    1,    # auto switch once asleep action (0=pause audio, 1=play local audio, anc off)
    0,
    0,    # tap controls DISABLED (0=tap controls enabled, 1=tap controls disabled)
    1,    # Noise canceling on/off prompt tone
    1,    # auto switch once asleep enabled
    0,
]

[[responses]]
# get earbuds auto stop timer
command = [21, 3]
response = [
    0,  # auto stop timer enabled
    30, # duration in minutes (i16), app allows up to 4h (240m)
    0,  # duration in minutes second byte
    1,  # unknown
    60, # time left (i32)
    0,
    0,
    0,  # time left end
]

[[responses]]
command = [1, 166]
response = [249, 243, 79, 106, 14, 112, 227, 230, 106, 12]

[[responses]]
# get alarms
command = [20, 1]
response = [
    0,          # alarm 1 id
    0,          # alarm 1 enabled
    149,        # alarm 1 time (in minutes since 00:00, little endian)
    1,          # alarm 1 time (in minutes since 00:00, little endian)
    0b00000000, # alarm 1 repeat (sun, mon, tues, wed, thurs, fri, sat, unused) 0=no repeat
    3,          # alarm 1 wake up tune (0=nature, 1=glow, 2=rhythm, 3=bloom)
    50,         # alarm 1 volume
    10,         # alarm 1 snooze duration in minutes (app allows 0=off, 5m, and 10m)
    1,          # alarm 2 id
    1,          # alarm 2 enabled
    149,        # alarm 2 time (in minutes since 00:00, little endian)
    2,          # alarm 2 time (in minutes since 00:00, little endian)
    0b10000000, # alarm 2 repeat (sun, mon, tues, wed, thurs, fri, sat, unused) 0=no repeat
    0,          # alarm 2 wake up tune (0=nature, 1=glow, 2=rhythm, 3=bloom)
    75,         # alarm 2 volume
    5,          # alarm 2 snooze duration in minutes (app allows 0=off, 5m, and 10m)
]

[[responses]]
command = [20, 2]
response = [255, 255, 255, 255, 255, 255, 255, 255]
