run-filtered-logs level='debug':
    RUST_LOG=none,openscq30_lib={{level}},openscq30_gui={{level}},openscq30_i18n={{level}} cargo run

build profile='dev':
    cargo build --profile {{profile}}

test:
    cargo test --bins

test-cov:
    cargo llvm-cov --no-report --bins

install path:
    ./scripts/install.sh "{{path}}"

uninstall path:
    ./scripts/uninstall.sh "{{path}}"

format:
    cargo fmt

format-check:
    cargo fmt --check
