build profile='dev':
    cargo build --profile {{profile}}

test:
    cargo test --bins
    # TODO integration tests
    # cargo test --test '*'

test-cov:
    cargo llvm-cov --no-report --bins
    # TODO integration tests
    # cargo llvm-cov --no-report --test '*'

install path:
    ./scripts/install.sh "{{path}}"

uninstall path:
    ./scripts/uninstall.sh "{{path}}"

alias fmt := format
format:
    cargo fmt

format-check:
    cargo fmt --check
