build profile='dev':
    #!/usr/bin/env bash
    set -euo pipefail

    case "{{profile}}" in
        dev)
            ./gradlew assembleBluetoothDebug
            ;;
        release)
            ./gradlew assembleBluetoothRelease
            ;;
        *)
            echo Invalid profile
            exit 1
    esac

test:
    cargo test
    ./gradlew testBluetoothDebugUnitTest

test-cov:
    cargo llvm-cov --no-report

format:
    #!/usr/bin/env bash
    cargo fmt

    if command -v ktlint > /dev/null; then
        ktlint --editorconfig=../.editorconfig -F
    else
        ./gradlew ktlintFormat
    fi

format-check:
    cargo fmt --check
    ./gradlew ktlintCheck
