.TH openscq30 1

.Sh NAME
.B openscq30
- Control Soundcore devices via Bluetooth

.SH SYNOPSIS
.B openscq30
.RB [OPTION]
.RB [--SUB-OPTION]
.RB [COMMAND]
.SH DESCRIPTION
.B openscq30
makes extensive use of subcommands. Each subcommand can have its own options, and the options for a given subcommand must come before any following subcommands. See the positioning of --mac-address in the following examples:
.RS
.nf
$ openscq30 device --mac-address AA:AA:AA:AA:AA:AA list-settings
$ openscq30 device --mac-address AA:AA:AA:AA:AA:AA setting --get autoPowerOff
$ openscq30 device --mac-address AA:AA:AA:AA:AA:AA setting --set autoPowerOff=60m
.fi
.RE

.SH OPTIONS
.TP
.B device
.br
Device Settings

.TP
.B paired-devices
Add Bluetooth devices to openscq30. The device needs to be paired using your operating system's Bluetooth controls before it can be paired with openscq30.

.TP
.B list-models
List all supported device models and their names

.TP
.B completions
Generate shell completions

.TP
.B help
.br
Show the help message





.SH
.B Options and their relative commands

.SS
.br
.SS
.B device
This option allows you to view or edit Soundcore device options. The device needs to be added to openscq30 with the "paired-devices" option first.
You need to use
.B -a or --mac-address
to specify the device.


.TP
.B list-settings
Allows you to view all current settings for a given device. You can always refer to "openscq30 device -a MAC_ADDRESS list-settings --help" for a more detailed help message.

.RS
.B OPTIONS
.RE
.RS
--no-categories         Don't display category headers
.RE
.RS
--no-extended-info      Don't display setting information in addition to the setting id
.RE
.RS
-j, --json              Output as JSON
.RE
.RS
-h, --help              Print very detailed help message (useful for advanced users)
.RE

.RS
All controls exposed by openscq30 have a unique setting id. Those settings can
be of varying types, such as a toggle, select, range, etc. Setting categories
are only used for showing related settings together to the user. They aren't
used otherwise.

This will list all settings that are currently available. Available settings may
change depending on the device's state. As an example, some devices only support
some features on newer firmware versions.

If \fB--no-extended-info\fR is not used, the type of setting as well as its
parameters will be output in addition to the setting id.

The format of this command's output is only stable in \fB--json\fR mode. The format
of the non-json output may change between versions, so \fB--json\fR should always be
used for scripts.

The equalizer setting has one quirk to be aware of, and that's the fractional
digits field. If fractional digits is 1, then 134 would mean 13.4. If it were 2,
then 1.34, and so on.


.RE




.TP
.B setting
You can use
.B --get
to retrieve the value of a specific setting, or
.B --set
to set a value. You might want to use
.B list-settings
first. You can always refer to "openscq30 device -a MAC_ADDRESS setting --help" for a more detailed help message.




.RS
.B Options
.RE
.RS
-g, --get <SETTING_ID>        Gets the value of a setting
.RE
.RS
-s, --set <SETTING_ID=VALUE>  Sets the value of a setting.
.RE
.RS
-j, --json                    Output as JSON
.RE
.RS
-h, --help                    Print very detailed help message (useful for advanced users)
.RE

.RS
\fB--get\fR and \fB--set\fR may be used multiple times to get/set multiple settings.
Operations will be executed in the order of the arguments. A get before a set
will print the original value, and a get after a set will print the value it was
set to.

Most value types are straight forward. For strings and numbers, enter the value
as is. There are some exceptions:

Optional selects: To deselect the value, set it to an empty string: \fB--set example=\fR

Modifiable selects: Prefix with '+' to add an item to the list, or '-' to remove
an item from the list. The prefix can be escaped with '\\'. Examples:
.IP
Create a new equalizer profile named "new profile"
.nf
.B
--set "customEqualizerProfile=+new profile"
.fi
.PP

.IP
Delete an equalizer profile named "new profile"
.nf
.B
--set "customEqualizerProfile=-new profile"
.fi
.PP

.IP
Activate an equalizer profile named "+new profile"
.nf
.B
--set "customEqualizerProfile=\+new profile"
.fi
.PP

Equalizers: All bands must be specified, and numbers should be separated with ','. Examples:
.IP
\fB--set volumeAdjustments -40,-30,-20,-10,0,1,2,3\fR when fractional digits is 1
(see \fBopenscq30 device list-settings --help\fR for info on fractional digits) will
assign [-4, -3, -2, -1, 0, 0.1, 0.2, 0.3].
.PP
.RE

.SS
.B paired-devices
Add/remove/list devices to openscq30


.TP
.B list, ls
List added devices

.RS
.B OPTIONS
.RE
.RS
-j, --json  Output as JSON
.RE
.RS
-h, --help  Print help
.RE

.RS
By default, this will output a table with a column for device model, mac
address, and if it's a demo or real device.
JSON output (--json) is recommended for scripts. It will instead output an array
of objects with the previously mentioned columns as keys instead.
.RE

.TP
.B add
.br
Add a paired device to openscq30

.RS
.B OPTIONS
.RE
.RS
-a, --mac-address <MAC_ADDRESS>  Device's mac address
.RE
.RS
-m, --model <MODEL>              Device model
.RE
.RS
--demo                           Enable demo mode for the device
.RE
.RS
-h, --help                       Print help
.RE

.RS
openscq30 needs to know what model your device is. This is where you provide the
necessary information to be able to connect to a device. It should already be
paired using Bluetooth at this point.

See \fBopenscq30 list-models\fR for a list of supported device models. This should
also be used to find the model id if you only know the name. Soundcore Life Q30
is SoundcoreA3028 for example.
.RE

.TP
.B remove
.br
Remove added devices from openscq30

.RS
.B OPTIONS
.RE
.RS
-a, --mac-address <MAC_ADDRESS>  Device's mac address
.RE
.RS
-h, --help                       Print help
.RE

.TP
.B help
.br
Prints a help message


.SS
.B list-models
List all supported device models and their names

.RS
.B OPTIONS
.RE
.RS
-j, --json  Output as JSON
.RE
.RS
-h, --help  Print help
.RE

.RS
Device models are locale-independent identifiers for each device. This command
will list all models as well as their names in English. Used for \fBopenscq30 paired-devices add --model\fR.
.RE


.SS
.B completions
Generate Shell completions

.RS
.B OPTIONS
.RE
.RS
-s, --shell <SHELL>  Target shell to generate completions for [possible values: bash, elvish, fish, powershell, zsh]
.RE
.RS
-h, --help           Print help
.RE



.SH
.B Initial Setup Guide
This guide is intended for new users. It will describe how to add a device to openscq30 and the basics of changing the device settings.

.TP
.B 1-) Pair and Connect via Bluetooth
Before starting, you should pair and connect to the device with the Bluetooth manager of your choosing.

.TP
.B 2-) Find the Device model name
Run
.B "openscq30 list-models"
and find your device. At the left side of the table, you will see something like:
.B "SoundcoreAXXXX".
Copy or remember the one that matches your device.
For example, "Soundcore Space One" is "SoundcoreA3035"

.RS
.TP
.B 2.1-)[Optional]  Having trouble finding your device?
You can also run
.B "openscq30 list-models | grep -i 'YOUR MODEL NAME'"
to make finding it easier.
.RE

.TP
.B 3-) Adding your device to openscq30
In order to change the device settings, you first need to add it to openscq30 with the model number we just found, plus the mac address of the device. You can use the Bluetooth manager of your choosing to find the mac address of the device.

.B openscq30 paired-devices add -a MAC_ADDRESS -m SoundcoreAxxxx

If you see \fBPaired\fR, you have successfully added your device to openscq30.


.SS
.B Basics of adjusting the device settings
For more info go to
.B setting
under
.B Options and their relative commands

.TP
.B 1-) Finding the available Settings
Each device can have different settings. To list the settings that are available for your device, run
.B openscq30 device -a MAC_ADDRESS  list-settings

.TP
.B 2-) Adjusting the settings
If you ran the previous command, you will see a list of all of the available settings for that device. Settings accept various different types of options such as integer ranges, toggles, and selects.
Integer ranges allow you to select a number from within a range (given in the list-settings output). A toggle is simply on/off. Selects allows you to select one of multiple options for that setting (also given in the list-settings output).

.RS
.TP
2.1-) Examples of changing a "select" setting
.RE
.RS
.B openscq30 device -a MAC_ADDRESS setting --set autoPowerOff=120m
.RE
.RE
.RS
.B openscq30 device -a MAC_ADDRESS setting --set autoPowerOff=30m
.RE

.RS
These may seem like "integer range", but if we look at the
.B list-settings
output, we can see it is a "select" that only allows: "disabled", "30m", "60m", "90m", "120m".
.RE


.RS
.TP
2.2-) Examples of changing a "integer range" setting
.RE
.RS
.B openscq30 device -a MAC_ADDRESS setting --set manualNoiseCanceling=1
.RE
.RS
.B openscq30 device -a MAC_ADDRESS setting --set manualNoiseCanceling=5
.RE


.RS
.TP
2.3-) Examples of changing a "toggle" setting

First we have to get the current state of this setting.

.B openscq30 device -a MAC_ADDRESS setting  --get  lowBatteryPrompt

In my case, this was "true". Now lets set it to "false".

.B openscq30 device -a MAC_ADDRESS setting  --set  lowBatteryPrompt=false
.RE
