// Automatically generated by flapigen
package com.oppzippy.openscq30.lib;
import androidx.annotation.NonNull;

public final class EqualizerBandOffsets {

    public EqualizerBandOffsets(@NonNull byte [] volume_offsets) {
        mNativeObj = init(volume_offsets);
    }
    private static native long init(byte [] volume_offsets);

    public final byte [] volumeOffsets() {
        byte [] ret = do_volumeOffsets(mNativeObj);

        return ret;
    }
    private static native byte [] do_volumeOffsets(long self);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ EqualizerBandOffsets(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}