// Automatically generated by flapigen
package com.oppzippy.openscq30.lib;
import androidx.annotation.NonNull;

public final class HelloWorldRust {

    public HelloWorldRust() {
        mNativeObj = init();
    }
    private static native long init();

    public final @NonNull String greet(@NonNull String to) {
        String ret = do_greet(mNativeObj, to);

        return ret;
    }
    private static native @NonNull String do_greet(long self, @NonNull String to);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ HelloWorldRust(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}