// Automatically generated by flapigen
package com.oppzippy.openscq30.lib;


public enum NoiseCancelingMode {
    Transport(0),
    Outdoor(1),
    Indoor(2);

    private final int value;
    NoiseCancelingMode(int value) {
        this.value = value;
    }
    public final int getValue() { return value; }
    /*package*/ static NoiseCancelingMode fromInt(int x) {
        switch (x) {
            case 0: return Transport;
            case 1: return Outdoor;
            case 2: return Indoor;
            default: throw new Error("Invalid value for enum NoiseCancelingMode: " + x);
        }
    }
}
