// Automatically generated by flapigen
package com.oppzippy.openscq30.lib;
import androidx.annotation.NonNull;

public final class SetAmbientSoundModePacket {

    public SetAmbientSoundModePacket(@NonNull AmbientSoundMode ambient_sound_mode, @NonNull NoiseCancelingMode noise_canceling_mode) {
        int a0 = ambient_sound_mode.getValue();        int a1 = noise_canceling_mode.getValue();
        mNativeObj = init(a0, a1);
        JNIReachabilityFence.reachabilityFence2(ambient_sound_mode, noise_canceling_mode);
    }
    private static native long init(int ambient_sound_mode, int noise_canceling_mode);

    public final short [] bytes() {
        short [] ret = do_bytes(mNativeObj);

        return ret;
    }
    private static native short [] do_bytes(long self);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ SetAmbientSoundModePacket(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}