// Automatically generated by flapigen
package com.oppzippy.openscq30.lib;
import androidx.annotation.NonNull;

public final class SoundcoreDevice {

    public SoundcoreDevice() {
        mNativeObj = init();
    }
    private static native long init();

    public final @NonNull String macAddress() throws Exception {
        String ret = do_macAddress(mNativeObj);

        return ret;
    }
    private static native @NonNull String do_macAddress(long self) throws Exception;

    public final @NonNull String name() throws Exception {
        String ret = do_name(mNativeObj);

        return ret;
    }
    private static native @NonNull String do_name(long self) throws Exception;

    public final AmbientSoundMode ambientSoundMode() {
        int ret = do_ambientSoundMode(mNativeObj);
        AmbientSoundMode convRet = AmbientSoundMode.fromInt(ret);

        return convRet;
    }
    private static native int do_ambientSoundMode(long self);

    public final void setAmbientSoundMode(@NonNull AmbientSoundMode ambient_sound_mode) throws Exception {
        int a0 = ambient_sound_mode.getValue();
        do_setAmbientSoundMode(mNativeObj, a0);

        JNIReachabilityFence.reachabilityFence1(ambient_sound_mode);
    }
    private static native void do_setAmbientSoundMode(long self, int ambient_sound_mode) throws Exception;

    public final NoiseCancelingMode noiseCancelingMode() {
        int ret = do_noiseCancelingMode(mNativeObj);
        NoiseCancelingMode convRet = NoiseCancelingMode.fromInt(ret);

        return convRet;
    }
    private static native int do_noiseCancelingMode(long self);

    public final void setNoiseCancelingMode(@NonNull NoiseCancelingMode noise_canceling_mode) throws Exception {
        int a0 = noise_canceling_mode.getValue();
        do_setNoiseCancelingMode(mNativeObj, a0);

        JNIReachabilityFence.reachabilityFence1(noise_canceling_mode);
    }
    private static native void do_setNoiseCancelingMode(long self, int noise_canceling_mode) throws Exception;

    public final @NonNull EqualizerConfiguration equalizerConfiguration() {
        long ret = do_equalizerConfiguration(mNativeObj);
        EqualizerConfiguration convRet = new EqualizerConfiguration(InternalPointerMarker.RAW_PTR, ret);

        return convRet;
    }
    private static native long do_equalizerConfiguration(long self);

    public final void setEqualizerConfiguration(@NonNull EqualizerConfiguration configuration) throws Exception {
        long a0 = configuration.mNativeObj;
        configuration.mNativeObj = 0;

        do_setEqualizerConfiguration(mNativeObj, a0);

        JNIReachabilityFence.reachabilityFence1(configuration);
    }
    private static native void do_setEqualizerConfiguration(long self, long configuration) throws Exception;

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ SoundcoreDevice(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}