// Automatically generated by flapigen
package com.oppzippy.openscq30.lib;
import androidx.annotation.NonNull;

public final class VolumeAdjustments {

    public VolumeAdjustments(@NonNull byte [] volume_adjustments) {
        mNativeObj = init(volume_adjustments);
    }
    private static native long init(byte [] volume_adjustments);

    public final byte [] adjustments() {
        byte [] ret = do_adjustments(mNativeObj);

        return ret;
    }
    private static native byte [] do_adjustments(long self);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ VolumeAdjustments(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}