// Automatically generated by flapigen
package com.oppzippy.openscq30.lib.bindings;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

public final class CustomHearId {
    @Override
    public boolean equals(Object obj) {
        if (obj instanceof CustomHearId)
            return ((CustomHearId)obj).rustEq(this);
        return false;
    }


    private final boolean rustEq(@NonNull CustomHearId other) {
        long a0 = other.mNativeObj;
        boolean ret = do_rustEq(mNativeObj, a0);

        JNIReachabilityFence.reachabilityFence1(other);

        return ret;
    }
    private static native boolean do_rustEq(long self, long other);

    public CustomHearId(boolean is_enabled, @NonNull StereoVolumeAdjustments volume_adjustments, int time, short hear_id_type, short hear_id_music_type, @Nullable StereoVolumeAdjustments custom_volume_adjustments) {
        long a1 = volume_adjustments.mNativeObj;
        volume_adjustments.mNativeObj = 0;

        long a5 = 0;//TODO: use ptr::null() for corresponding constant
        if (custom_volume_adjustments != null) {
            a5 = custom_volume_adjustments.mNativeObj;
            custom_volume_adjustments.mNativeObj = 0;
        }

        mNativeObj = init(is_enabled, a1, time, hear_id_type, hear_id_music_type, a5);
        JNIReachabilityFence.reachabilityFence2(volume_adjustments, custom_volume_adjustments);
    }
    private static native long init(boolean is_enabled, long volume_adjustments, int time, short hear_id_type, short hear_id_music_type, long custom_volume_adjustments);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ CustomHearId(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}