// Automatically generated by flapigen
package com.oppzippy.openscq30.lib.bindings;


public final class CustomNoiseCanceling {

    public CustomNoiseCanceling(short value) {
        mNativeObj = init(value);
    }
    private static native long init(short value);

    public final short value() {
        short ret = do_value(mNativeObj);

        return ret;
    }
    private static native short do_value(long self);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ CustomNoiseCanceling(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}