// Automatically generated by flapigen
package com.oppzippy.openscq30.lib.bindings;
import androidx.annotation.NonNull;

public final class CustomNoiseCanceling {
    @Override
    public boolean equals(Object obj) {
        if (obj instanceof CustomNoiseCanceling)
            return ((CustomNoiseCanceling)obj).rustEq(this);
        return false;
    }


    private final boolean rustEq(@NonNull CustomNoiseCanceling other) {
        long a0 = other.mNativeObj;
        boolean ret = do_rustEq(mNativeObj, a0);

        JNIReachabilityFence.reachabilityFence1(other);

        return ret;
    }
    private static native boolean do_rustEq(long self, long other);

    public CustomNoiseCanceling(short value) {
        mNativeObj = init(value);
    }
    private static native long init(short value);

    public final short value() {
        short ret = do_value(mNativeObj);

        return ret;
    }
    private static native short do_value(long self);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ CustomNoiseCanceling(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}