// Automatically generated by flapigen
package com.oppzippy.openscq30.lib.bindings;


public final class DeviceFeatureFlags {

    public static native int soundModes();

    public static native int noiseCancelingMode();

    public static native int customNoiseCanceling();

    public static native int transparencyModes();

    public static native int hearId();

    public static native int equalizer();

    public static native int customButtonModel();

    public static native int wearDetection();

    public static native int touchTone();

    public static native int autoPowerOff();

    public static native int twoChannelEqualizer();

    public static native int dynamicRangeCompression();

    private DeviceFeatureFlags() {}
}