// Automatically generated by flapigen
package com.oppzippy.openscq30.lib.bindings;
import androidx.annotation.NonNull;

public final class InboundPacket {

    public InboundPacket(@NonNull byte [] input) throws Exception {
        mNativeObj = init(input);
    }
    private static native long init(byte [] input) throws Exception;

    public final @NonNull java.util.Optional<SoundModeUpdatePacket> soundModeUpdate() {
        long ret = do_soundModeUpdate(mNativeObj);
        java.util.Optional<SoundModeUpdatePacket> convRet;
        if (ret != 0) {
            convRet = java.util.Optional.of(new SoundModeUpdatePacket(InternalPointerMarker.RAW_PTR, ret));
        } else {
            convRet = java.util.Optional.empty();
        }

        return convRet;
    }
    private static native long do_soundModeUpdate(long self);

    public final @NonNull java.util.Optional<SetSoundModeOkPacket> setSoundModeOk() {
        long ret = do_setSoundModeOk(mNativeObj);
        java.util.Optional<SetSoundModeOkPacket> convRet;
        if (ret != 0) {
            convRet = java.util.Optional.of(new SetSoundModeOkPacket(InternalPointerMarker.RAW_PTR, ret));
        } else {
            convRet = java.util.Optional.empty();
        }

        return convRet;
    }
    private static native long do_setSoundModeOk(long self);

    public final @NonNull java.util.Optional<SetEqualizerOkPacket> setEqualizerOk() {
        long ret = do_setEqualizerOk(mNativeObj);
        java.util.Optional<SetEqualizerOkPacket> convRet;
        if (ret != 0) {
            convRet = java.util.Optional.of(new SetEqualizerOkPacket(InternalPointerMarker.RAW_PTR, ret));
        } else {
            convRet = java.util.Optional.empty();
        }

        return convRet;
    }
    private static native long do_setEqualizerOk(long self);

    public final @NonNull java.util.Optional<StateUpdatePacket> stateUpdate() {
        long ret = do_stateUpdate(mNativeObj);
        java.util.Optional<StateUpdatePacket> convRet;
        if (ret != 0) {
            convRet = java.util.Optional.of(new StateUpdatePacket(InternalPointerMarker.RAW_PTR, ret));
        } else {
            convRet = java.util.Optional.empty();
        }

        return convRet;
    }
    private static native long do_stateUpdate(long self);

    public final @NonNull java.util.Optional<SetEqualizerWithDrcOkPacket> setEqualizerWithDrcOk() {
        long ret = do_setEqualizerWithDrcOk(mNativeObj);
        java.util.Optional<SetEqualizerWithDrcOkPacket> convRet;
        if (ret != 0) {
            convRet = java.util.Optional.of(new SetEqualizerWithDrcOkPacket(InternalPointerMarker.RAW_PTR, ret));
        } else {
            convRet = java.util.Optional.empty();
        }

        return convRet;
    }
    private static native long do_setEqualizerWithDrcOk(long self);

    public final @NonNull java.util.Optional<BatteryChargingUpdatePacket> batteryChargingUpdate() {
        long ret = do_batteryChargingUpdate(mNativeObj);
        java.util.Optional<BatteryChargingUpdatePacket> convRet;
        if (ret != 0) {
            convRet = java.util.Optional.of(new BatteryChargingUpdatePacket(InternalPointerMarker.RAW_PTR, ret));
        } else {
            convRet = java.util.Optional.empty();
        }

        return convRet;
    }
    private static native long do_batteryChargingUpdate(long self);

    public final @NonNull java.util.Optional<BatteryLevelUpdatePacket> batteryLevelUpdate() {
        long ret = do_batteryLevelUpdate(mNativeObj);
        java.util.Optional<BatteryLevelUpdatePacket> convRet;
        if (ret != 0) {
            convRet = java.util.Optional.of(new BatteryLevelUpdatePacket(InternalPointerMarker.RAW_PTR, ret));
        } else {
            convRet = java.util.Optional.empty();
        }

        return convRet;
    }
    private static native long do_batteryLevelUpdate(long self);

    public final @NonNull java.util.Optional<ChineseVoicePromptStateUpdatePacket> chineseVoicePromptStateUpdate() {
        long ret = do_chineseVoicePromptStateUpdate(mNativeObj);
        java.util.Optional<ChineseVoicePromptStateUpdatePacket> convRet;
        if (ret != 0) {
            convRet = java.util.Optional.of(new ChineseVoicePromptStateUpdatePacket(InternalPointerMarker.RAW_PTR, ret));
        } else {
            convRet = java.util.Optional.empty();
        }

        return convRet;
    }
    private static native long do_chineseVoicePromptStateUpdate(long self);

    public final @NonNull java.util.Optional<FirmwareVersionUpdatePacket> firmwareVersionUpdate() {
        long ret = do_firmwareVersionUpdate(mNativeObj);
        java.util.Optional<FirmwareVersionUpdatePacket> convRet;
        if (ret != 0) {
            convRet = java.util.Optional.of(new FirmwareVersionUpdatePacket(InternalPointerMarker.RAW_PTR, ret));
        } else {
            convRet = java.util.Optional.empty();
        }

        return convRet;
    }
    private static native long do_firmwareVersionUpdate(long self);

    public final @NonNull java.util.Optional<LdacStateUpdatePacket> ldacStateUpdate() {
        long ret = do_ldacStateUpdate(mNativeObj);
        java.util.Optional<LdacStateUpdatePacket> convRet;
        if (ret != 0) {
            convRet = java.util.Optional.of(new LdacStateUpdatePacket(InternalPointerMarker.RAW_PTR, ret));
        } else {
            convRet = java.util.Optional.empty();
        }

        return convRet;
    }
    private static native long do_ldacStateUpdate(long self);

    public final @NonNull java.util.Optional<TwsStatusUpdatePacket> twsStatusUpdate() {
        long ret = do_twsStatusUpdate(mNativeObj);
        java.util.Optional<TwsStatusUpdatePacket> convRet;
        if (ret != 0) {
            convRet = java.util.Optional.of(new TwsStatusUpdatePacket(InternalPointerMarker.RAW_PTR, ret));
        } else {
            convRet = java.util.Optional.empty();
        }

        return convRet;
    }
    private static native long do_twsStatusUpdate(long self);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ InboundPacket(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}