// Automatically generated by flapigen
package com.oppzippy.openscq30.lib.bindings;


public enum NoiseCancelingModeType {
    None(0),
    Basic(1),
    Custom(2);

    private final int value;
    NoiseCancelingModeType(int value) {
        this.value = value;
    }
    public final int getValue() { return value; }
    /*package*/ static NoiseCancelingModeType fromInt(int x) {
        switch (x) {
            case 0: return None;
            case 1: return Basic;
            case 2: return Custom;
            default: throw new Error("Invalid value for enum NoiseCancelingModeType: " + x);
        }
    }
}
