// Automatically generated by flapigen
package com.oppzippy.openscq30.lib.bindings;
import androidx.annotation.NonNull;

public final class SetEqualizerAndCustomHearIdPacket {
    @Override
    public boolean equals(Object obj) {
        if (obj instanceof SetEqualizerAndCustomHearIdPacket)
            return ((SetEqualizerAndCustomHearIdPacket)obj).rustEq(this);
        return false;
    }


    private final boolean rustEq(@NonNull SetEqualizerAndCustomHearIdPacket other) {
        long a0 = other.mNativeObj;
        boolean ret = do_rustEq(mNativeObj, a0);

        JNIReachabilityFence.reachabilityFence1(other);

        return ret;
    }
    private static native boolean do_rustEq(long self, long other);

    public SetEqualizerAndCustomHearIdPacket(@NonNull EqualizerConfiguration equalizer_configuration, @NonNull Gender gender, @NonNull AgeRange age_range, @NonNull CustomHearId custom_hear_id) {
        long a0 = equalizer_configuration.mNativeObj;
        equalizer_configuration.mNativeObj = 0;

        long a1 = gender.mNativeObj;
        gender.mNativeObj = 0;

        long a2 = age_range.mNativeObj;
        age_range.mNativeObj = 0;

        long a3 = custom_hear_id.mNativeObj;
        custom_hear_id.mNativeObj = 0;

        mNativeObj = init(a0, a1, a2, a3);
        JNIReachabilityFence.reachabilityFence4(equalizer_configuration, gender, age_range, custom_hear_id);
    }
    private static native long init(long equalizer_configuration, long gender, long age_range, long custom_hear_id);

    public final byte [] bytes() {
        byte [] ret = do_bytes(mNativeObj);

        return ret;
    }
    private static native byte [] do_bytes(long self);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ SetEqualizerAndCustomHearIdPacket(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}