// Automatically generated by flapigen
package com.oppzippy.openscq30.lib.bindings;
import androidx.annotation.NonNull;

public final class SoundModeUpdatePacket {
    @Override
    public boolean equals(Object obj) {
        if (obj instanceof SoundModeUpdatePacket)
            return ((SoundModeUpdatePacket)obj).rustEq(this);
        return false;
    }


    private final boolean rustEq(@NonNull SoundModeUpdatePacket other) {
        long a0 = other.mNativeObj;
        boolean ret = do_rustEq(mNativeObj, a0);

        JNIReachabilityFence.reachabilityFence1(other);

        return ret;
    }
    private static native boolean do_rustEq(long self, long other);

    public SoundModeUpdatePacket() throws Exception {
        mNativeObj = init();
    }
    private static native long init() throws Exception;

    public final AmbientSoundMode ambientSoundMode() {
        int ret = do_ambientSoundMode(mNativeObj);
        AmbientSoundMode convRet = AmbientSoundMode.fromInt(ret);

        return convRet;
    }
    private static native int do_ambientSoundMode(long self);

    public final NoiseCancelingMode noiseCancelingMode() {
        int ret = do_noiseCancelingMode(mNativeObj);
        NoiseCancelingMode convRet = NoiseCancelingMode.fromInt(ret);

        return convRet;
    }
    private static native int do_noiseCancelingMode(long self);

    public final TransparencyMode transparencyMode() {
        int ret = do_transparencyMode(mNativeObj);
        TransparencyMode convRet = TransparencyMode.fromInt(ret);

        return convRet;
    }
    private static native int do_transparencyMode(long self);

    public final @NonNull CustomNoiseCanceling customNoiseCanceling() {
        long ret = do_customNoiseCanceling(mNativeObj);
        CustomNoiseCanceling convRet = new CustomNoiseCanceling(InternalPointerMarker.RAW_PTR, ret);

        return convRet;
    }
    private static native long do_customNoiseCanceling(long self);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ SoundModeUpdatePacket(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}