// Automatically generated by flapigen
package com.oppzippy.openscq30.lib.bindings;
import androidx.annotation.NonNull;

public final class SoundModeProfile {

    public SoundModeProfile(@NonNull NoiseCancelingModeType noise_canceling_mode_type, @NonNull TransparencyModeType transparency_mode_type) {
        int a0 = noise_canceling_mode_type.getValue();        int a1 = transparency_mode_type.getValue();
        mNativeObj = init(a0, a1);
        JNIReachabilityFence.reachabilityFence2(noise_canceling_mode_type, transparency_mode_type);
    }
    private static native long init(int noise_canceling_mode_type, int transparency_mode_type);

    public final NoiseCancelingModeType noiseCancelingModeType() {
        int ret = do_noiseCancelingModeType(mNativeObj);
        NoiseCancelingModeType convRet = NoiseCancelingModeType.fromInt(ret);

        return convRet;
    }
    private static native int do_noiseCancelingModeType(long self);

    public final TransparencyModeType transparencyModeType() {
        int ret = do_transparencyModeType(mNativeObj);
        TransparencyModeType convRet = TransparencyModeType.fromInt(ret);

        return convRet;
    }
    private static native int do_transparencyModeType(long self);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ SoundModeProfile(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}