// Automatically generated by flapigen
package com.oppzippy.openscq30.lib.bindings;
import androidx.annotation.NonNull;

public final class SoundcoreDeviceUtils {

    public static native boolean isMacAddressSoundcoreDevice(@NonNull String mac_address);

    public static native boolean isSoundcoreServiceUuid(long most_significant_bits, long least_significant_bits);

    public static native @NonNull String readCharacteristicUuid();

    public static native @NonNull String writeCharacteristicUuid();

    private SoundcoreDeviceUtils() {}
}