// Automatically generated by flapigen
package com.oppzippy.openscq30.lib.bindings;


public enum TransparencyModeType {
    Basic(0),
    Custom(1);

    private final int value;
    TransparencyModeType(int value) {
        this.value = value;
    }
    public final int getValue() { return value; }
    /*package*/ static TransparencyModeType fromInt(int x) {
        switch (x) {
            case 0: return Basic;
            case 1: return Custom;
            default: throw new Error("Invalid value for enum TransparencyModeType: " + x);
        }
    }
}
