// Automatically generated by flapigen
package com.oppzippy.openscq30.lib.bindings;
import androidx.annotation.NonNull;

public final class VolumeAdjustments {
    @Override
    public boolean equals(Object obj) {
        if (obj instanceof VolumeAdjustments)
            return ((VolumeAdjustments)obj).rustEq(this);
        return false;
    }


    private final boolean rustEq(@NonNull VolumeAdjustments other) {
        long a0 = other.mNativeObj;
        boolean ret = do_rustEq(mNativeObj, a0);

        JNIReachabilityFence.reachabilityFence1(other);

        return ret;
    }
    private static native boolean do_rustEq(long self, long other);

    public VolumeAdjustments(@NonNull double [] volume_adjustments) {
        mNativeObj = init(volume_adjustments);
    }
    private static native long init(double [] volume_adjustments);

    public final double [] adjustments() {
        double [] ret = do_adjustments(mNativeObj);

        return ret;
    }
    private static native double [] do_adjustments(long self);

    public static native double minVolume();

    public static native double maxVolume();

    public static native double step();

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ VolumeAdjustments(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}