// Automatically generated by flapigen
package com.oppzippy.openscq30.libbindings;


public enum PresetEqualizerProfile {
    SoundcoreSignature(0),
    Acoustic(1),
    BassBooster(2),
    BassReducer(3),
    Classical(4),
    Podcast(5),
    Dance(6),
    Deep(7),
    Electronic(8),
    Flat(9),
    HipHop(10),
    Jazz(11),
    Latin(12),
    Lounge(13),
    Piano(14),
    Pop(15),
    RnB(16),
    Rock(17),
    SmallSpeakers(18),
    SpokenWord(19),
    TrebleBooster(20),
    TrebleReducer(21);

    private final int value;
    PresetEqualizerProfile(int value) {
        this.value = value;
    }
    public final int getValue() { return value; }
    /*package*/ static PresetEqualizerProfile fromInt(int x) {
        switch (x) {
            case 0: return SoundcoreSignature;
            case 1: return Acoustic;
            case 2: return BassBooster;
            case 3: return BassReducer;
            case 4: return Classical;
            case 5: return Podcast;
            case 6: return Dance;
            case 7: return Deep;
            case 8: return Electronic;
            case 9: return Flat;
            case 10: return HipHop;
            case 11: return Jazz;
            case 12: return Latin;
            case 13: return Lounge;
            case 14: return Piano;
            case 15: return Pop;
            case 16: return RnB;
            case 17: return Rock;
            case 18: return SmallSpeakers;
            case 19: return SpokenWord;
            case 20: return TrebleBooster;
            case 21: return TrebleReducer;
            default: throw new Error("Invalid value for enum PresetEqualizerProfile: " + x);
        }
    }
}
