// Automatically generated by flapigen
package com.oppzippy.openscq30.libbindings;
import androidx.annotation.NonNull;

public final class SoundcoreDeviceUtils {

    public static native boolean isMacAddressSoundcoreDevice(@NonNull String mac_address);

    public static native @NonNull String serviceUuid();

    public static native @NonNull String readCharacteristicUuid();

    public static native @NonNull String writeCharacteristicUuid();

    private SoundcoreDeviceUtils() {}
}