name: build

on: push

permissions:
  contents: read

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - uses: dtolnay/rust-toolchain@stable

      - name: Build cli and gui
        shell: C:\Program Files\Git\bin\bash.exe
        run: cargo build --release --package openscq30-cli --package openscq30-gui
      - name: Build installer
        shell: bash
        run: ./packaging/windows/build.sh

      - name: Move to artifacts directory
        run: |
          New-Item -Type Directory -Path artifacts
          Move-Item target\release\openscq30.exe artifacts\openscq30-cli-windows-x86_64.exe
          Move-Item .\packaging\windows\Output\OpenSCQ30-Setup.exe artifacts\openscq30-gui-windows-x86_64.exe

      - name: Upload artifacts
        uses: actions/upload-artifact@v5
        with:
          name: windows
          path: artifacts/*
