name: lint

on:
  - push
  - pull_request

permissions:
  contents: read

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Install just
        run: sudo snap install just --classic
      - name: Install rust
        run: rustup install stable
      - name: Install ktlint
        run: |
          curl --silent --show-error --remote-name-all --location https://github.com/pinterest/ktlint/releases/download/1.8.0/ktlint{,.asc}
          curl -sS https://raw.githubusercontent.com/pinterest/ktlint/1e1cdd6b3c7dfc94c9418c7c4706c0dcffcb132c/public-key.asc | gpg --import
          gpg --verify ktlint.asc
          chmod a+x ktlint && sudo mv ktlint /usr/local/bin/
      - name: Check formatting
        run: just format-check

  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Install shellcheck
        run: sudo apt-get install -y shellcheck fd-find
      - name: Install just
        run: sudo snap install just --classic
      - name: Run shellcheck
        run: just shellcheck
