name: test

on:
  push:
    paths-ignore: &push_paths_ignore
      - "*.md"
      - docs/**
      - fastlane/**
      - screenshots/**
      - tools/**
      - packaging/**
  pull_request:
    paths-ignore: *push_paths_ignore

permissions:
  contents: read

jobs:
  test-rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Install basic requirements
        run: sudo apt-get install -y pkg-config libdbus-1-dev libxkbcommon-dev
      - name: Install just
        run: sudo snap install just --classic
      - name: Install rust
        run: rustup install --profile minimal stable
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@80e6af7a2ec7f280fffe2d0a9d3a12a9d11d86e9 # v2.75.1
        with:
          tool: cargo-llvm-cov
      - name: Cache cargo dependencies
        uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2
      - name: Run all rust tests
        run: just test-cov
      - name: Generate HTML test coverage report
        run: just test-cov-report html
      - name: Upload coverage report
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: coverage
          path: target/llvm-cov/html/
