name: test windows

on:
  push:
    paths: &push_paths
      - Cargo.lock
      - lib/**
      - .github/workflows/test-windows.yml
  pull_request:
    paths: *push_paths

permissions:
  contents: read

jobs:
  # Only lib is tested on windows since building the gui/cli would take
  # a lot longer, and they don't contain any platform specific code
  test-rust:
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Install just
        run: choco install just
      - name: Install rust
        run: rustup install --profile minimal stable
      - name: Cache cargo dependencies
        uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2
      - name: Run lib tests
        run: just lib/ test
