name: validate fastlane metadata

on:
  push:
    paths: &push_paths
      - fastlane/**
      - .github/workflows/validate-fastlane-metadata.yml
  pull_request:
    paths: *push_paths

permissions:
  contents: read

jobs:
  validate-fastlane-metadata:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Validate fastlane metadata
        uses: ashutoshgngwr/validate-fastlane-supply-metadata@c8857fdbbd3e00f9a5cbe8604bcecfa95ce8fef8 # v2.1.0
