export RUSTFLAGS := "--cfg=web_sys_unstable_apis"

build:
    npm run build

_build-wasm:
    npm run build:wasm

test: (_build-wasm)
    cd wasm && cargo test
    npm run test
    npm run e2etest

test-cov:
    cd wasm && cargo llvm-cov --no-report

format:
    cd wasm && cargo fmt

format-check:
    cd wasm && cargo fmt --check
